### ISSUE TITLE
Low frame rate

### ISSUE THREAD

**Issue by Borgcubus** [Kanasaru/resa#2]
1920x1080 @22 fps is pretty low. There is definitely room for improvement

**Comment by Kanasaru** [comment]
It will be fixed after the 0.4.0 pre-release. The issue is based on the immense sprite usage for the water. This will be exchanged with a dynamically created background image. The first test has shown a big improvement in lower resolutions. In bigger resolutions, it will be possible to use another grid size (zoom).

**Comment by Kanasaru** [comment]
It's now fixed with the `v0.4.1-alpha` release. Higher resolutions will be still a problem, only got it around 29 fps @ 1080p but in lower resolutions, it's quite an improvement. Can't do anymore at this moment, that's why the issue is closed.
